apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: ner-spacy-en
  name: ner-spacy-en
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ner-spacy-en
    spec:
      containers:
      - env:
        - name: LANGUAGE
          value: en
        image: maven-taln.upf.edu/ner_spacy_en:20190705
        name: ner-spacy-en
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "1"
            memory: "4Gi"
          requests:
            cpu: "500m"
            memory: "1Gi"
      restartPolicy: Always
status: {}
