apiVersion: v1
kind: Service
metadata:
  labels:
    app: ner-spacy-en
  name: ner-spacy-en
spec:
  ports:
  - name: "8000"
    port: 8000
    targetPort: 8000
  selector:
    app: ner-spacy-en
status:
  loadBalancer: {}
